development:
  adapter: mysql2
  encoding: utf8
  database: cities_service_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: cities_service_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: cities_service_production
  username: root
  password:
  host: localhost
