test:
  host: tags-service-development.herokuapp.com
  port: 80
  api_version: 2

development:
  host: tags-service-development.herokuapp.com
  port: 80
  api_version: 2
  max_concurrency: 4

production:
  host: tags-service.herokuapp.com
  port: 80
  api_version: 2
  max_concurrency: 10
